# Generated by Django 6.0 on 2026-01-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UCCRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(blank=True, max_length=255, null=True)),
                ('document_link', models.CharField(blank=True, max_length=255, null=True)),
                ('record', models.CharField(blank=True, max_length=255, null=True)),
                ('record_link', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('lapse_date', models.CharField(blank=True, max_length=255, null=True)),
                ('debtor', models.CharField(blank=True, max_length=255, null=True)),
                ('secured_party', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'UCC record',
                'verbose_name_plural': 'UCC records',
            },
        ),
    ]
