# ============================================================
# Colorado UCC Records — Web Scraping & Database Integration
# ============================================================
#
# Purpose:
#   Automates searching and collecting UCC records from the
#   Colorado Secretary of State website using Playwright.
#
# Main tasks:
#   1. Launch Firefox using Playwright.
#   2. Open the Colorado UCC advanced search page.
#   3. Search for records by debtor/owner name.
#   4. Collect search results from the results table.
#   5. Open individual document records and capture their URLs.
#   6. Extract document, record, debtor, secured party, dates,
#      and record type information.
#   7. Save collected records to a Django database.
#   8. Skip records that already exist in the database.
#
# Technologies:
#   - Python
#   - Playwright
#   - Django
#   - Django ORM
#   - PostgreSQL/SQLite (depending on project configuration)
#   - asyncio
#
# Additional functionality:
#   - human_type() simulates human-like text input with random
#     delays between characters.
#   - save_in_db() uses Django ORM to create or retrieve records.
#   - collect_results() processes search results and extracts
#     structured data from the website.
#   - Playwright response handling is used to capture document
#     URLs generated by the website.
#
# Project integration:
#   - Uses Django models through parser_app.models.UCCRecord.
#   - Django environment is initialized through load_django.py.
#
# ============================================================


import asyncio
from pprint import pprint
import random
from asgiref.sync import sync_to_async
from playwright.async_api import async_playwright, Playwright, Page

from load_django import *
from parser_app.models import UCCRecord

async def human_type(locator, text, min_delay=0.09, max_delay=0.15):
    await locator.click()
    await locator.fill("")
    for char in text:
        await locator.type(char)
        await asyncio.sleep(random.uniform(min_delay, max_delay))

@sync_to_async
def save_in_db(data):
    ucc_record, created = UCCRecord.objects.get_or_create(
        document=data.get('document'),
        record=data.get('record'),
        defaults={
            'document_link': data.get('document_link'),
            'record_link': data.get('record_link'),
            'date': data.get('date'),
            'lapse_date': data.get('lapse_date'),
            'debtor': data.get('debtor'),
            'secured_party': data.get('secured_party'),
            'type': data.get('type'),
        }
    )

    if created:
        print(f"✅ Создана новая запись: {ucc_record}")
    else:
        print(f"ℹ Запись уже существует: {ucc_record}")

async def type_Debtor_Owner(page: Page, text):
    inpt = page.locator('//input[@id="advanceSearchForm:debtorName:organization"]')
    btn = page.locator('//input[@id="advanceSearchForm:searchBtnId"]')

    await asyncio.sleep(2)
    await human_type(inpt, text)
    await asyncio.sleep(1)

    await btn.scroll_into_view_if_needed()
    await asyncio.sleep(1)
    await btn.click()

responses = []

def handle_response(response):
    
    if "dynamiccontent.properties" in response.url and response.status == 200:
        try:
            responses.append(response)
            print(response)
        except:
            print("⚠️  Non-JSON response or failed to parse.")


async def collect_results(page: Page):
    full_result = []

    tbody = page.locator('//tbody[@id="searchResultForm:advSearchResultsId_data"]')
    rows = await tbody.locator('xpath=./tr').all()

    for row in rows:
        tds = await row.locator('xpath=./td').all()

        document = tds[2].locator('xpath=./a')
        record = tds[7].locator('xpath=./a')

        await asyncio.sleep(10)

        await document.scroll_into_view_if_needed()
        # await document.click()
        # page.on("response", handle_response)
        response = None
        async with page.expect_response(lambda response: "dynamiccontent.properties" in response.url) as response_info:
            await document.click()
            response = await response_info.value

        print(response)
        
        await asyncio.sleep(20)
        btn = page.locator('//input[@id="viewSearchPdfForm:prevBtn"]')
      
        await btn.scroll_into_view_if_needed()
        await asyncio.sleep(1)
        await btn.click()

        dt = {
            "document": await document.inner_text(),
            "document_link": response.url,
            "date": await tds[3].inner_text(),
            "debtor": await tds[4].inner_text(),
            "secured_party": await tds[5].inner_text(),
            "type": await tds[6].inner_text(),
            "record": await record.inner_text(),
            "record_link": response.url,
            "lapse_date": await tds[8].inner_text(),
        }

        pprint(dt)
        await save_in_db(dt)
        await asyncio.sleep(5)

        
        full_result.append(dt)
        await asyncio.sleep(4)


    return full_result

async def run(playwright: Playwright):
    browser = await playwright.firefox.launch(headless=False)
    page = await browser.new_page()

    await page.goto(
        "https://www.sos.state.co.us/ucc/pages/search/advanceSearch.xhtml",
        wait_until="networkidle",
    )

    await type_Debtor_Owner(page, "business")

    await page.wait_for_selector(
        '//tbody[@id="searchResultForm:advSearchResultsId_data"]/tr'
    )

    results = await collect_results(page)
    print(results)

    await browser.close()


async def main():
    async with async_playwright() as playwright:
        await run(playwright)


asyncio.run(main())
